[tool.poetry]
name = "freeroute"
version = "0.1.0"
description = ""
authors = ["Anton"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
netifaces = "^0.11.0"
pyyaml = "^6.0"
pydantic = "^1.10.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
